name: ticket_raising_management
description: "A Ticket Raising Project to maintain and raise tickets/issues."
version: 0.0.1
homepage: https://github.com/Santhoshcv19/ticket_raising

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod: ^2.4.9
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_crashlytics: ^3.4.8
  equatable: ^2.0.5
  dartz: ^0.10.1
  file_picker: ^6.1.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.9
  page_view_dot_indicator: ^2.3.0
  just_audio: ^0.9.36
  image_network: ^2.5.4+1
  path_provider: ^2.1.1
  syncfusion_flutter_pdfviewer: ^20.4.54
  video_player: ^2.8.2
  freezed_annotation: ^2.4.1
  fl_chart: ^0.66.1
  fluttertoast: ^8.2.4
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.6
  internet_file: ^1.2.0
  http: ^0.13.6
  url_launcher: ^6.2.5
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
